import 'dotenv/config'
import { PrismaClient } from '../src/generated/client'

const prisma = new PrismaClient()

const FACTS = [
  // Sciences
  { text: "Les abeilles peuvent reconnaître des visages humains en utilisant un processus similaire à celui des humains.", url: "https://fr.wikipedia.org/wiki/Abeille" },
  { text: "Un nuage pèse en moyenne 500 tonnes, soit l'équivalent de 100 éléphants.", url: "https://fr.wikipedia.org/wiki/Nuage" },
  { text: "Le cerveau humain consomme 20% de l'énergie totale du corps alors qu'il ne représente que 2% du poids corporel.", url: "https://fr.wikipedia.org/wiki/Cerveau" },
  { text: "L'ADN humain est composé de 3 milliards de paires de bases. Déployé, il ferait le tour du soleil et retour 600 fois.", url: "https://fr.wikipedia.org/wiki/ADN" },
  { text: "Les étoiles filantes ne sont pas des étoiles mais des grains de poussière cosmique brûlant dans l'atmosphère.", url: "https://fr.wikipedia.org/wiki/Météorite" },
  { text: "Le corps humain contient environ 0,2 mg d'or, principalement dans le sang.", url: "https://fr.wikipedia.org/wiki/Aurum" },
  { text: "La lumière du Soleil met 8 minutes et 20 secondes pour atteindre la Terre.", url: "https://fr.wikipedia.org/wiki/Vitesse_de_la_lumière" },
  { text: "Les champignons sont plus proches génétiquement des animaux que des plantes.", url: "https://fr.wikipedia.org/wiki/Champignon" },
  { text: "Un atome est composé à 99,99% de vide. Si un noyau atomique était une bille de marbre, les électrons seraient à un kilomètre.", url: "https://fr.wikipedia.org/wiki/Atome" },
  { text: "Le son ne se propage pas dans le vide spatial.", url: "https://fr.wikipedia.org/wiki/Son" },
  { text: "Les dauphins dorment avec un seul œil ouvert, la moitié de leur cerveau restant éveillée.", url: "https://fr.wikipedia.org/wiki/Dauphin" },
  { text: "La Terre perd environ 100 tonnes de matière par jour à cause du Soleil.", url: "https://fr.wikipedia.org/wiki/Vent_solaire" },
  { text: "Un jour sur Vénus est plus long qu'une année sur Vénus.", url: "https://fr.wikipedia.org/wiki/Vénus" },
  { text: "Les taches de rousseur sont génétiques : elles résultent d'une variante du gène MC1R.", url: "https://fr.wikipedia.org/wiki/Rousseur" },
  { text: "Le cerveau humain stocke environ 2,5 pétaoctets de données.", url: "https://fr.wikipedia.org/wiki/Cerveau" },
  { text: "Les particules de votre corps aujourd'hui ont été forgées dans les étoiles il y a des milliards d'années.", url: "https://fr.wikipedia.org/wiki/Nucléosynthèse" },
  { text: "L'eau peut bouillir et geler en même temps : c'est le point triple.", url: "https://fr.wikipedia.org/wiki/Point_triple" },
  { text: "Le corps humain renouvelle sa peau entièrement tous les 27 jours.", url: "https://fr.wikipedia.org/wiki/Peau" },
  { text: "Les asticots peuvent survivre dans un environnement radioactif 100 fois plus intense que celui qui tuerait un humain.", url: "https://fr.wikipedia.org/wiki/Diptère" },
  { text: "Le cri d'une baleine bleue est le son le plus fort du monde animal : 188 décibels.", url: "https://fr.wikipedia.org/wiki/Baleine_bleue" },
  { text: "Les rayons X traversent la chair mais pas les os, d'où leur découverte par Röntgen en 1895.", url: "https://fr.wikipedia.org/wiki/Rayons_X" },
  { text: "Le corps humain contient assez de carbone pour fabriquer 900 crayons.", url: "https://fr.wikipedia.org/wiki/Carbone" },
  { text: "Les papillons goûtent avec leurs pattes.", url: "https://fr.wikipedia.org/wiki/Papillon" },
  { text: "La Terre effectue 107 000 km/h dans l'espace.", url: "https://fr.wikipedia.org/wiki/Mouvement_de_la_Terre" },
  { text: "Les humains partagent 60% de leur ADN avec les bananes.", url: "https://fr.wikipedia.org/wiki/ADN" },

  // Histoire
  { text: "Cléopâtre a vécu plus près de l'invention de l'iPhone que de la construction des pyramides de Gizeh.", url: "https://fr.wikipedia.org/wiki/Cléopâtre" },
  { text: "La plus longue guerre de l'histoire durera 383 ans, entre les Pays-Bas et les îles Scilly (1651-2009).", url: "https://fr.wikipedia.org/wiki/Guerre_des_îles_Scilly" },
  { text: "Les Romains urineraient dans leurs pots de chambre. L'urine servait à tanner les peaux et blanchir les vêtements.", url: "https://fr.wikipedia.org/wiki/Urine" },
  { text: "Napoléon n'était pas petit : 1,70 m, la moyenne française de l'époque.", url: "https://fr.wikipedia.org/wiki/Napoléon_Ier" },
  { text: "En 1932, un avocat australien a tué un crocodile de 6 mètres et l'a utilisé comme mannequin pour son procès.", url: "https://fr.wikipedia.org/wiki/Crocodile_d'eau_douce" },
  { text: "La France s'est battue contre la Suisse lors d'une guerre qui a duré 300 ans sans une seule bataille : la Conquête du Jura.", url: "https://fr.wikipedia.org/wiki/Conquête_du_Jura" },
  { text: "Les femmes n'ont obtenu le droit de vote en France qu'en 1944.", url: "https://fr.wikipedia.org/wiki/Droit_de_vote_des_femmes" },
  { text: "En 1890, un journal américain a inventé le terme 'robot' en le traduisant du tchèque.", url: "https://fr.wikipedia.org/wiki/Robot" },
  { text: "L'empire mongol était le plus grand empire contigu de l'histoire, couvrant 24 millions de km².", url: "https://fr.wikipedia.org/wiki/Empire_mongol" },
  { text: "En 1904, le premier McDonald's a ouvert en 1940, pas en 1904.", url: "https://fr.wikipedia.org/wiki/McDonald%27s" },
  { text: "Les Égyptiens anciens inventèrent le dentifrice en mélangeant cendres de bouse de vache et sel.", url: "https://fr.wikipedia.org/wiki/Histoire_des_soins_dentaires" },
  { text: "Le mot 'virus' signifie 'poison' en latin.", url: "https://fr.wikipedia.org/wiki/Virus" },
  { text: "Le premier ordinateur de l'histoire pesait 27 tonnes : l'ENIAC, construit en 1945.", url: "https://fr.wikipedia.org/wiki/ENIAC" },
  { text: "Les Vikings portaient des casques à cornes... non, c'est un mythe inventé par les costumiers d'opéra.", url: "https://fr.wikipedia.org/wiki/Viking" },
  { text: "L'expression 'poser un lapin' vient du XIXe siècle : les filles qui attendaient un amoureux et qui n'était pas venu posaient un lapin sur leurs genoux.", url: "https://fr.wikipedia.org/wiki/Poser_un_lapin" },
  { text: "En 1774, un homme a été condamné à mort pour avoir volé une serviette.", url: "https://fr.wikipedia.org/wiki/Penne_d%27Agen" },
  { text: "Le code-barres a été inspiré par les bandes sur les verres de lunettes.", url: "https://fr.wikipedia.org/wiki/Code-barres" },
  { text: "Le premier selfie date de 1839 : un homme s'est photographié en utilisant un reflet dans une cuillère.", url: "https://fr.wikipedia.org/wiki/Selfie" },
  { text: "La tour de Pise penchait déjà avant d'être achevée, et on l'a même redressée pendant sa construction.", url: "https://fr.wikipedia.org/wiki/Tour_de_Pise" },
  { text: "L'expression 'casser les pieds' vient du XIXe siècle et désignait quelqu'un qui dérangeait dans son travail.", url: "https://fr.wikipedia.org/wiki/Casser_les_pieds" },
  { text: "Les anciens Égyptiens peignaient les hommes en rouge et les femmes en jaune pâle dans leurs fresques.", url: "https://fr.wikipedia.org/wiki/Art_de_l%27%C3%89gypte_ancienne" },
  { text: "Le Titanic avait un jumeau théorique : le Britannic, coulé pendant la Première Guerre mondiale comme hôpital flottant.", url: "https://fr.wikipedia.org/wiki/Britannic" },
  { text: "La première marque de chewing-gum était... un chewing-gum : le Wrigley's, lancé en 1892.", url: "https://fr.wikipedia.org/wiki/Wrigley%27s" },
  { text: "Les Gaulois ne portaient pas de casques à cornes. C'est une invention du XIXe siècle.", url: "https://fr.wikipedia.org/wiki/Gaulois" },
  { text: "Le mot 'hasard' vient de l'arabe 'al-zahr' qui signifie 'le dé'.", url: "https://fr.wikipedia.org/wiki/Hasard" },

  // Technologie
  { text: "Le premier site web au monde a été créé par Tim Berners-Lee en 1991. Il est toujours visible à CERN.", url: "https://fr.wikipedia.org/wiki/Site_web" },
  { text: "80% de la puissance de calcul d'un smartphone est gaspillée quand on ne l'utilise pas activement.", url: "https://fr.wikipedia.org/wiki/Smartphone" },
  { text: "Le premier bug informatique était un vrai insecte : un papillon de nuit dans un ordinateur Harvard en 1947.", url: "https://fr.wikipedia.org/wiki/Bug_informatique" },
  { text: "Les emails représentent 88% du trafic internet mondial. L'email est toujours le roi du web.", url: "https://fr.wikipedia.org/wiki/Email" },
  { text: "Le premier message SMS envoyé le 3 décembre 1992 disait 'Merry Christmas'.", url: "https://fr.wikipedia.org/wiki/Message_texte" },
  { text: "Le WiFi utilise des ondes radio, pas des ondes électromagnétiques invisibles magiques.", url: "https://fr.wikipedia.org/wiki/Wi-Fi" },
  { text: "Un datacenter consomme autant d'électricité qu'une ville de 100 000 habitants.", url: "https://fr.wikipedia.org/wiki/Datacenter" },
  { text: "La première caméra de surveillance a été installée en 1942 aux Pays-Bas pour observer les lanceurs de fusées V2.", url: "https://fr.wikipedia.org/wiki/Cam%C3%A9ra_de_surveillance" },
  { text: "Le premier moteur de recherche s'appelait Archie et datait de 1990.", url: "https://fr.wikipedia.org/wiki/Archie" },
  { text: "Le mot 'Google' vient de 'googol', le chiffre 1 suivi de 100 zéros.", url: "https://fr.wikipedia.org/wiki/Google" },
  { text: "Le premier virus informatique date de 1986 : le 'Brain', un virus de boot sector.", url: "https://fr.wikipedia.org/wiki/Virus_informatique" },
  { text: "Le Bluetooth doit son nom à un roi danois du Xᵉ siècle, Harald Blåtand, qui unifia la Scandinavie.", url: "https://fr.wikipedia.org/wiki/Bluetooth" },
  { text: "Le premier clic commercial sur Google a été vendu pour 25 cents en 1998.", url: "https://fr.wikipedia.org/wiki/Google" },
  { text: "Le premier iPhone (2007) n'avait pas de clavier physique ni de copier-coller. Steve Jobs pensait que le tactile suffisait.", url: "https://fr.wikipedia.org/wiki/IPhone" },
  { text: "Le réseau électrique mondial consomme 15% de l'énergie produite juste pour les pertes en transit.", url: "https://fr.wikipedia.org/wiki/R%C3%A9seau_%C3%A9lectrique" },
  { text: "Le mot 'emoji' vient du japonais : 'e' (image) + 'moji' (caractère).", url: "https://fr.wikipedia.org/wiki/Emoji" },
  { text: "Le premier site de partage vidéo, YouTube, a été créé en février 2005. Le premier vidéo 'Me at the zoo' date du 23 avril 2005.", url: "https://fr.wikipedia.org/wiki/YouTube" },
  { text: "Le WiFi a été inventé par Hedy Lamarr, actrice de Hollywood, qui était aussi inventrice.", url: "https://fr.wikipedia.org/wiki/H%C3%A9tzy_Lamarr" },
  { text: "Le premier mot réservé sur Internet était 'Hello, World!', créé en 1972 par Brian Kernighan.", url: "https://fr.wikipedia.org/wiki/Hello,_World!" },
  { text: "Les serveurs de Google contiennent environ 2,5 millions de disques durs au total.", url: "https://fr.wikipedia.org/wiki/Google" },
  { text: "Le premier ordinateur personnel pesait 1 tonne : l'Altair 8800 (1975).", url: "https://fr.wikipedia.org/wiki/Altair_8800" },
  { text: "Le premier programme informatique a été écrit par Ada Lovelace en 1843, pour la machine analytique de Babbage.", url: "https://fr.wikipedia.org/wiki/Ada_Lovelace" },
  { text: "Le mot 'spam' vient d'une sketch des Monty Python où le mot est répété indéfiniment dans un restaurant.", url: "https://fr.wikipedia.org/wiki/Spam" },
  { text: "Le premier réseau social s'appelait SixDegrees (1997) et permettait de créer un profil et lister ses amis.", url: "https://fr.wikipedia.org/wiki/SixDegrees" },
  { text: "Le premier logo de Apple avait été dessiné par Isaac Newton sous un arbre. Il a été simplifié en 1977.", url: "https://fr.wikipedia.org/wiki/Logo_d%27Apple" },

  // Gastronomie
  { text: "Le miel ne se périme jamais. Des pots de miel de 3000 ans ont été trouvés dans des tombes égyptiennes, encore comestibles.", url: "https://fr.wikipedia.org/wiki/Miel" },
  { text: "Les fraises sont les seuls fruits dont les graines sont à l'extérieur.", url: "https://fr.wikipedia.org/wiki/Fraise" },
  { text: "Le chocolat chaud était la boisson sacrée des Aztèques, où il servait de monnaie.", url: "https://fr.wikipedia.org/wiki/Chocolat" },
  { text: "Un avocat est botaniquement un fruit, pas un légume.", url: "https://fr.wikipedia.org/wiki/Avocat" },
  { text: "Les cacahuètes ne sont pas des noix mais des légumineuses, comme les pois.", url: "https://fr.wikipedia.org/wiki/Cacahu%C3%A8te" },
  { text: "Le ketchup a été vendu au XIXe siècle comme remède contre la diarrhée.", url: "https://fr.wikipedia.org/wiki/Ketchup" },
  { text: "Les pommes contiennent 25% d'air, ce qui explique pourquoi elles flottent.", url: "https://fr.wikipedia.org/wiki/Pomme" },
  { text: "Le wasabi servi dans la plupart des restaurants n'est pas du vrai wasabi : c'est de la moutarde teinte en vert.", url: "https://fr.wikipedia.org/wiki/Wasabi" },
  { text: "La vanille est la seule fruit de l'orchidée comestible. Il faut la polliniser à la main.", url: "https://fr.wikipedia.org/wiki/Vanille" },
  { text: "Les tomates étaient considérées comme toxiques en Europe au XVIe siècle car les riches mangeaient dessus dans des assiettes de plomb.", url: "https://fr.wikipedia.org/wiki/Tomate" },
  { text: "Le premier fast-food était un restaurant de frites ouvert à Paris en 1834.", url: "https://fr.wikipedia.org/wiki/Frite" },
  { text: "Le sucre a été utilisé comme monnaie d'échange au Moyen Âge, d'où le mot 'salary' (salary = salaire).", url: "https://fr.wikipedia.org/wiki/Sucre" },
  { text: "Les carottes n'étaient pas orange à l'origine : elles étaient violettes. Les Néerlandais les ont sélectionnées en orange pour le roi d'Orange.", url: "https://fr.wikipedia.org/wiki/Carotte" },
  { text: "Le pain est le premier aliment transformé de l'histoire humaine, datant de 14 000 ans avant l'agriculture.", url: "https://fr.wikipedia.org/wiki/Pain" },
  { text: "Le champagne mousseux a été inventé par accident au XVIIe siècle.", url: "https://fr.wikipedia.org/wiki/Champagne" },
  { text: "Les bananes sont des baies, mais les fraises ne le sont pas.", url: "https://fr.wikipedia.org/wiki/Banane" },
  { text: "Le premier McDonald's de France a ouvert à Mulhouse en 1979.", url: "https://fr.wikipedia.org/wiki/McDonald%27s" },
  { text: "Le café était considéré comme une boisson diabolique au XVIIe siècle. Le pape Clément VIII l'a 'baptisé' après l'avoir goûté.", url: "https://fr.wikipedia.org/wiki/Caf%C3%A9" },
  { text: "Le premier chewing-gum était de la cire d'abeille mâchée. Les Amérindiens le mâchaient depuis des millénaires.", url: "https://fr.wikipedia.org/wiki/Chewing-gum" },
  { text: "Les huîtres sont des hermaphrodites qui changent de sexe au cours de leur vie.", url: "https://fr.wikipedia.org/wiki/Hu%C3%AEtre" },
  { text: "Le mot 'restaurant' vient du bouillon réparateur ('restoratif') servi au XVIIIe siècle.", url: "https://fr.wikipedia.org/wiki/Restaurant" },
  { text: "Le premier plat cuisiné congelé a été inventé par Clarence Birdseye en 1923 : des légumes surgelés.", url: "https://fr.wikipedia.org/wiki/Clarence_Birdseye" },
  { text: "L'huile d'olive est utilisée depuis 6000 ans en Méditerranée.", url: "https://fr.wikipedia.org/wiki/Huile_d%27olive" },
  { text: "Le chocolat a été consommé comme boisson pendant 3000 ans avant d'être transformé en barre solide en 1847.", url: "https://fr.wikipedia.org/wiki/Chocolat" },
  { text: "Les oignons sont un remède contre les piqûres d'insectes : la sève coupée absorbe le venin.", url: "https://fr.wikipedia.org/wiki/Oignon" },

  // Langue & Culture
  { text: "Le mot 'éternel' contient 'ternel' qui n'existe pas, mais 'éternité' contient 'ternité'.", url: "https://fr.wikipedia.org/wiki/Langue_fran%C3%A7aise" },
  { text: "Le français est la première langue parlée sur 5 continents.", url: "https://fr.wikipedia.org/wiki/Langue_fran%C3%A7aise" },
  { text: "Le mot 'hasard' vient de l'arabe 'az-zahr' signifiant 'le dé'.", url: "https://fr.wikipedia.org/wiki/Hasard" },
  { text: "L'expression 'avoir le cafard' vient du XIXe siècle : le cafard était alors le nom de la mélancolie.", url: "https://fr.wikipedia.org/wiki/Cafard" },
  { text: "Le mot 'choc' est un mot français qui a été emprunté à l'anglais.", url: "https://fr.wikipedia.org/wiki/Choc" },
  { text: "La lettre 'j' n'a été ajoutée à l'alphabet français qu'au XVIe siècle.", url: "https://fr.wikipedia.org/wiki/Lettre_j" },
  { text: "Le mot 'robot' vient du tchèque 'robota' qui signifie 'travail forcé'.", url: "https://fr.wikipedia.org/wiki/Robot" },
  { text: "Le français a plus de 30 mots pour dire 'amour'.", url: "https://fr.wikipedia.org/wiki/Amour" },
  { text: "L'expression 'être dans la lune' date du XIXe siècle.", url: "https://fr.wikipedia.org/wiki/%C3%8Atre_dans_la_lune" },
  { text: "Le mot 'agenda' signifie 'ce qui doit être fait', pas 'carnet de rendez-vous'.", url: "https://fr.wikipedia.org/wiki/Agenda" },
  { text: "Le français est la seule langue où 'l'ordre alphabétique' commence par 'a'.", url: "https://fr.wikipedia.org/wiki/Alphabet" },
  { text: "L'expression 'tomber dans les pommes' viendrait de 'dans les state de pommes' (état de pommes/évanouissement).", url: "https://fr.wikipedia.org/wiki/Tomber_dans_les_pommes" },
  { text: "Le mot 'caca' est le seul mot français qui ne rime avec rien.", url: "https://fr.wikipedia.org/wiki/Rime" },
  { text: "Le mot 'gaffe' vient du norvégien 'gaffa' signifiant 'pince'.", url: "https://fr.wikipedia.org/wiki/Gaffe" },
  { text: "Le mot 'bistro' vient du russe 'bystro' (vite), prononcé par les soldats alliés en 1918.", url: "https://fr.wikipedia.org/wiki/Bistro" },
  { text: "Le mot 'chouchou' vient de l'occitan 'chuchau' qui signifie 'chéri'.", url: "https://fr.wikipedia.org/wiki/Chouchou" },
  { text: "Le mot 'hasard' a été introduit en français par les croisés ramenant des dés d'Orient.", url: "https://fr.wikipedia.org/wiki/Hasard" },
  { text: "Le mot 'jazz' vient du français 'jas' (bruit, agitation) au départ.", url: "https://fr.wikipedia.org/wiki/Jazz" },
  { text: "Le mot 'blues' vient de 'blue devils' (démons bleus), l'expression anglaise pour la mélancolie.", url: "https://fr.wikipedia.org/wiki/Blues" },
  { text: "Le mot 'quartier' vient du latin 'quadrarius' signifiant 'un quart'.", url: "https://fr.wikipedia.org/wiki/Quartier" },
  { text: "Le mot 'salon' vient de 'salone', un grand hall en italien.", url: "https://fr.wikipedia.org/wiki/Salon" },
  { text: "Le mot 'canard' est utilisé en français depuis le XIIe siècle pour désigner un faux journal.", url: "https://fr.wikipedia.org/wiki/Canard_encha%C3%AEn%C3%A9" },
  { text: "Le mot 'poussière' a 12 lettres et ne contient aucune voyelle répétée.", url: "https://fr.wikipedia.org/wiki/Poussi%C3%A8re" },
  { text: "Le mot 'choc' est un emprunt au français fait à l'anglais au XXe siècle.", url: "https://fr.wikipedia.org/wiki/Choc" },
  { text: "Le mot 'chouchou' vient de l'occitan 'chuchau' signifiant 'chéri'.", url: "https://fr.wikipedia.org/wiki/Chouchou" },

  // Géographie
  { text: "La Russie couvre 11 fuseaux horaires, plus que tout autre pays.", url: "https://fr.wikipedia.org/wiki/Russie" },
  { text: "L'Afrique est le seul continent à s'étendre d'un pôle à l'autre.", url: "https://fr.wikipedia.org/wiki/Afrique" },
  { text: "Le désert le plus chaud du monde n'est pas le Sahara mais l'Atacama au Chili.", url: "https://fr.wikipedia.org/wiki/Atacama" },
  { text: "La France a 12 fuseaux horaires, plus que le Japon.", url: "https://fr.wikipedia.org/wiki/France" },
  { text: "Le point le plus profond de l'océan (Mariana, 10 994 m) serait assez profond pour submerger l'Everest avec 2 km de marge.", url: "https://fr.wikipedia.org/wiki/Fosse_des_Marianes" },
  { text: "L'Islande et le Groenland ont des noms trompeurs : l'Islande est verte et le Groenland est blanc.", url: "https://fr.wikipedia.org/wiki/Groenland" },
  { text: "Le lac Baïkal en Sibérie contient 20% de l'eau douce liquide non gelée de la Terre.", url: "https://fr.wikipedia.org/wiki/Ba%C3%AFkal" },
  { text: "L'Antarctique est le continent le plus sec, le plus venteux et le plus froid de la Terre.", url: "https://fr.wikipedia.org/wiki/Antarctique" },
  { text: "Le mont Everest grandit de 4 mm par an à cause du mouvement des plaques tectoniques.", url: "https://fr.wikipedia.org/wiki/Mont_Everest" },
  { text: "Le Nil et l'Amazone se disputent le titre du plus long fleuve du monde depuis des siècles.", url: "https://fr.wikipedia.org/wiki/Fleuve" },
  { text: "Le Sahara s'est étendu et rétracté cycliquement tous les 20 000 ans depuis 40 000 ans.", url: "https://fr.wikipedia.org/wiki/Sahara" },
  { text: "La Chine a construit un mur de 13 000 km pour empêcher l'avancée du désert de Gobi.", url: "https://fr.wikipedia.org/wiki/Gobi" },
  { text: "Le pôle Nord magnétique se déplace de 55 km par an vers la Sibérie.", url: "https://fr.wikipedia.org/wiki/P%C3%B4le_Nord_magn%C3%A9tique" },
  { text: "L'île de Pâques a 887 statues de pierre appelées moaï, toutes orientées vers l'intérieur de l'île.", url: "https://fr.wikipedia.org/wiki/%C3%8Ele_de_P%C3%A2ques" },
  { text: "Le volcan Krakatoa en 1883 a été entendu à 4 800 km de distance.", url: "https://fr.wikipedia.org/wiki/Krakatoa" },
  { text: "Le Canada a plus de lacs que tous les autres pays réunis.", url: "https://fr.wikipedia.org/wiki/Lac" },
  { text: "La Norvège a plus de 238 000 km de côtes si on compte les fjords.", url: "https://fr.wikipedia.org/wiki/C%C3%B4te" },
  { text: "Le plus grand désert du monde est l'Antarctique, avec 14 millions de km².", url: "https://fr.wikipedia.org/wiki/D%C3%A9sert" },
  { text: "La mer Morte est si salée (34%) qu'on ne peut pas y couler mais flotter dessus.", url: "https://fr.wikipedia.org/wiki/Mer_Morte" },
  { text: "Le point le plus chaud de la Terre (Darvaza, Turkménistan) brûle depuis 1971.", url: "https://fr.wikipedia.org/wiki/Porte_de_l%27Enfer" },

  // Animaux
  { text: "Les pieuvres ont 3 cœurs et du sang bleu.", url: "https://fr.wikipedia.org/wiki/Pieuvre" },
  { text: "Les tigres ont des rayures sur la peau, pas seulement sur le pelage.", url: "https://fr.wikipedia.org/wiki/Tigre" },
  { text: "Un requin peut sentir une goutte de sang dans 100 litres d'eau.", url: "https://fr.wikipedia.org/wiki/Requin" },
  { text: "Les flamants roses sont gris à la naissance et deviennent roses grâce à leur alimentation.", url: "https://fr.wikipedia.org/wiki/Flamant_rose" },
  { text: "Les escargots peuvent dormir pendant 3 ans.", url: "https://fr.wikipedia.org/wiki/Escargot" },
  { text: "Les girafes ont la langue violette, probablement pour se protéger du soleil.", url: "https://fr.wikipedia.org/wiki/Girafe" },
  { text: "Les koalas ont des empreintes digitales quasi identiques à celles des humains.", url: "https://fr.wikipedia.org/wiki/Koala" },
  { text: "Les éléphants sont les seuls mammifères qui ne sautent pas.", url: "https://fr.wikipedia.org/wiki/%C3%89l%C3%A9phant" },
  { text: "Les pingouins proposent un caillou à leur partenaire pour sceller l'union.", url: "https://fr.wikipedia.org/wiki/Pingouin" },
  { text: "Les tortues peuvent respirer par leur derrière (cloaque).", url: "https://fr.wikipedia.org/wiki/Tortue" },
  { text: "Le hamster peut porter 16 bébés à la fois.", url: "https://fr.wikipedia.org/wiki/Hamster" },
  { text: "Les chauves-souris sont les seuls mammifères capables de vol actif.", url: "https://fr.wikipedia.org/wiki/Chauve-souris" },
  { text: "Les fourmis pèsent plus lourd que tous les humains réunis.", url: "https://fr.wikipedia.org/wiki/Fourmi" },
  { text: "Le cheval marin mâle est le seul mâle au monde qui porte les bébés et accouche.", url: "https://fr.wikipedia.org/wiki/Hippocampe" },
  { text: "Les dauphins se donnent des noms : chaque dauphin a un sifflement signature unique.", url: "https://fr.wikipedia.org/wiki/Dauphin" },
  { text: "Les ours polaires ont la peau noire sous leur fourrure blanche.", url: "https://fr.wikipedia.org/wiki/Ours_polair" },
  { text: "Les papillons monarques parcourent 4 000 km pour migrer du Canada au Mexique.", url: "https://fr.wikipedia.org/wiki/Papillon_monarque" },
  { text: "Les grenouilles bondissantes peuvent sauter 20 fois leur longueur.", url: "https://fr.wikipedia.org/wiki/Grenouille" },
  { text: "Les requins existent depuis plus longtemps que les arbres : 400 millions d'années.", url: "https://fr.wikipedia.org/wiki/Requin" },
  { text: "Les lions dorment 20 heures par jour.", url: "https://fr.wikipedia.org/wiki/Lion" },
  { text: "Les perroquets peuvent apprendre plus de 100 mots et comprendre leur signification.", url: "https://fr.wikipedia.org/wiki/Perroquet" },
  { text: "Les baleines à bosse chantent des chansons qui évoluent chaque année.", url: "https://fr.wikipedia.org/wiki/Baleine_%C3%A0_bosse" },
  { text: "Les escargots de jardin peuvent creuser jusqu'à 30 cm dans le sol.", url: "https://fr.wikipedia.org/wiki/Escargot" },
  { text: "Les abeilles peuvent voler à 40 km/h et visitent 2 millions de fleurs pour 1 kg de miel.", url: "https://fr.wikipedia.org/wiki/Abeille" },
  { text: "Les loutres de mer se tiennent par la patte pour ne pas dériver pendant leur sommeil.", url: "https://fr.wikipedia.org/wiki/Loutre_de_mer" },

  // Espace
  { text: "Sur la Lune, un pas équivaut à 6 pas sur Terre.", url: "https://fr.wikipedia.org/wiki/Lune" },
  { text: "Il pleut du verre sur Neptune et Uranie : des diamants même sur Jupiter.", url: "https://fr.wikipedia.org/wiki/Neptune_(plan%C3%A8te)" },
  { text: "Une journée sur Vénus dure 243 jours terrestres, mais une année vénusienne ne fait que 225 jours.", url: "https://fr.wikipedia.org/wiki/V%C3%A9nus" },
  { text: "La tache rouge de Jupiter est une tempête qui fait 3 fois la taille de la Terre.", url: "https://fr.wikipedia.org/wiki/Grosse_Tache_Rouge" },
  { text: "La NASA a confirmé la présence d'eau sur la Lune en 2009.", url: "https://fr.wikipedia.org/wiki/Eau" },
  { text: "L'espace est complètement silencieux car il n'y a pas d'atmosphère pour propager le son.", url: "https://fr.wikipedia.org/wiki/Vide" },
  { text: "Le Soleil représente 99,86% de la masse totale du système solaire.", url: "https://fr.wikipedia.org/wiki/Soleil" },
  { text: "La Terre est le seul planète non nommée d'après un dieu grec ou romain.", url: "https://fr.wikipedia.org/wiki/Terre" },
  { text: "Un voyage vers Proxima Centauri (l'étoile la plus proche) prendrait 73 000 ans à la vitesse actuelle.", url: "https://fr.wikipedia.org/wiki/Proxima_Centauri" },
  { text: "Les trous noirs peuvent atteindre plusieurs milliards de fois la masse du Soleil.", url: "https://fr.wikipedia.org/wiki/Trou_noir" },
  { text: "La lumière de la Lune met 1,3 seconde pour atteindre la Terre.", url: "https://fr.wikipedia.org/wiki/Lune" },
  { text: "Il y a plus d'étoiles dans l'univers que de grains de sable sur toutes les plages de la Terre.", url: "https://fr.wikipedia.org/wiki/%C3%89toile" },
  { text: "L'anneau de Saturne s'étend sur 282 000 km mais ne fait que 10 mètres d'épaisseur.", url: "https://fr.wikipedia.org/wiki/Anneaux_de_Saturne" },
  { text: "La sonde Voyager 1, lancée en 1977, est l'objet humain le plus éloigné de la Terre.", url: "https://fr.wikipedia.org/wiki/Voyager_1" },
  { text: "Le trou noir le plus proche de la Terre (Gaia BH1) est à 1 560 années-lumière.", url: "https://fr.wikipedia.org/wiki/Trou_noir" },
  { text: "La Grande Tache Rouge de Jupiter est une tempête active depuis au moins 350 ans.", url: "https://fr.wikipedia.org/wiki/Grosse_Tache_Rouge" },
  { text: "Les planètes n'ont pas de vraie couleur : elles reflètent la lumière du Soleil.", url: "https://fr.wikipedia.org/wiki/Plan%C3%A8te" },
  { text: "Le plus grand volcan du système solaire est Olympus Mons sur Mars, 3 fois l'Everest.", url: "https://fr.wikipedia.org/wiki/Olympus_Mons" },
  { text: "La Terre a été frappée par des météorites chaque jour pendant les 4,5 milliards d'années de son histoire.", url: "https://fr.wikipedia.org/wiki/M%C3%A9t%C3%A9orite" },
  { text: "L'univers observable a un diamètre de 93 milliards d'années-lumière.", url: "https://fr.wikipedia.org/wiki/Univers" },
  { text: "Chaque année, 40 000 tonnes de poussière cosmique tombent sur la Terre.", url: "https://fr.wikipedia.org/wiki/Poussi%C3%A8re_cosmique" },
  { text: "La Lune s'éloigne de 3,8 cm par an.", url: "https://fr.wikipedia.org/wiki/Lune" },
  { text: "Les étoiles filantes ne sont pas des étoiles mais des météoroïdes entrant dans l'atmosphère.", url: "https://fr.wikipedia.org/wiki/%C3%89toile_filante" },
  { text: "Le Soleil se déplace à 220 km/s autour du centre de la Voie lactée.", url: "https://fr.wikipedia.org/wiki/Soleil" },
  { text: "Le premier satellite artificiel (Spoutnik 1) a été lancé le 4 octobre 1957.", url: "https://fr.wikipedia.org/wiki/Spoutnik_1" },

  // Corps humain
  { text: "Le cœur humain bat environ 100 000 fois par jour.", url: "https://fr.wikipedia.org/wiki/C%C5%93ur" },
  { text: "L'estomac produit une nouvelle couche de mucus tous les 2 semaines pour ne pas se digérer lui-même.", url: "https://fr.wikipedia.org/wiki/Estomac" },
  { text: "Les humains perdent 600 000 particules de peau chaque heure.", url: "https://fr.wikipedia.org/wiki/Peau" },
  { text: "Le foie est le seul organe capable de se régénérer entièrement.", url: "https://fr.wikipedia.org/wiki/Foie" },
  { text: "Les os du corps humain sont plus nombreux chez les bébés (300) que chez les adultes (206).", url: "https://fr.wikipedia.org/wiki/Os" },
  { text: "Le cerveau humain génère assez d'électricité pour allumer une petite ampoule.", url: "https://fr.wikipedia.org/wiki/Cerveau" },
  { text: "Les humains produisent environ 1 litre de salive par jour.", url: "https://fr.wikipedia.org/wiki/Salive" },
  { text: "Le nez humain peut mémoriser et reconnaître 50 000 odeurs différentes.", url: "https://fr.wikipedia.org/wiki/Nez" },
  { text: "Le corps humain contient environ 5 litres de sang.", url: "https://fr.wikipedia.org/wiki/Sang" },
  { text: "Les ongles des mains poussent 4 fois plus vite que ceux des pieds.", url: "https://fr.wikipedia.org/wiki/Ongle" },
  { text: "Le nez et les oreilles ne cessent jamais de grandir.", url: "https://fr.wikipedia.org/wiki/Nez" },
  { text: "Le corps humain contient assez de fer pour fabriquer un clou de 3 cm.", url: "https://fr.wikipedia.org/wiki/Fer" },
  { text: "Les larmes contiennent 98% d'eau et des anticorps.", url: "https://fr.wikipedia.org/wiki/Larme" },
  { text: "Le ventre humain produit de l'acide chlorhydrique capable de dissoudre le métal.", url: "https://fr.wikipedia.org/wiki/Acide_chlorhydrique" },
  { text: "Les sourcils ont un cycle de vie de 3 à 4 mois avant de tomber.", url: "https://fr.wikipedia.org/wiki/Sourcil" },
  { text: "Le squelette humain se renouvelle entièrement tous les 10 ans.", url: "https://fr.wikipedia.org/wiki/Squelette" },
  { text: "Les humains partagent 99,9% de leur ADN avec tous les autres humains.", url: "https://fr.wikipedia.org/wiki/ADN" },
  { text: "Le cerveau humain utilise 20% de l'oxygène du corps.", url: "https://fr.wikipedia.org/wiki/Cerveau" },
  { text: "Le corps humain contient 78% d'eau.", url: "https://fr.wikipedia.org/wiki/Eau" },
  { text: "Les muscles des yeux bougent environ 100 000 fois par jour.", url: "https://fr.wikipedia.org/wiki/%C5%92il" },
  { text: "Le cœur humain produit assez de pression pour projeter du sang à 9 mètres.", url: "https://fr.wikipedia.org/wiki/C%C5%93ur" },
  { text: "Le corps humain contient assez de soufre pour tuer un chat.", url: "https://fr.wikipedia.org/wiki/Soufre" },
  { text: "Les humains produisent 0,5 litre de sueur par jour en moyenne.", url: "https://fr.wikipedia.org/wiki/Sueur" },
  { text: "Le pancréas produit de l'insuline, une hormone essentielle pour réguler le sucre.", url: "https://fr.wikipedia.org/wiki/Pancr%C3%A9as" },
  { text: "Le corps humain contient assez de carbone pour fabriquer 900 crayons.", url: "https://fr.wikipedia.org/wiki/Carbone" },

  // Arts & Culture
  { text: "La Joconde sourit-elle vraiment ? Les scientifiques ont prouvé que son sourire est une illusion optique.", url: "https://fr.wikipedia.org/wiki/Joconde" },
  { text: "Le premier film d'animation de Disney était Blanche-Neige en 1937.", url: "https://fr.wikipedia.org/wiki/Blanche-Neige_et_les_Sept_Nains_(film)" },
  { text: "Les monuments de l'île de Pâques ont été sculptés sans outils métalliques.", url: "https://fr.wikipedia.org/wiki/%C3%8Ele_de_P%C3%A2ques" },
  { text: "Le plus long roman de l'histoire fait 3,2 millions de caractères : 'Les Chouans' de Balzac.", url: "https://fr.wikipedia.org/wiki/Litt%C3%A9rature" },
  { text: "Le piano a 88 touches : 52 blanches et 36 noires.", url: "https://fr.wikipedia.org/wiki/Piano" },
  { text: "Le premier film d'animation japonais 'Astro Boy' a été diffusé en 1963.", url: "https://fr.wikipedia.org/wiki/Astro_Boy" },
  { text: "Les égyptiens peignaient les hommes en rouge et les femmes en jaune dans leurs fresques.", url: "https://fr.wikipedia.org/wiki/Art_de_l%27%C3%89gypte_ancienne" },
  { text: "Le plus vieux jeu vidéo connu date de 2600 avant JC : Senet, un jeu de plateau égyptien.", url: "https://fr.wikipedia.org/wiki/Senet" },
  { text: "Le premier roman policier de l'histoire est 'Le Crime de la rue Morgue' de Poe en 1841.", url: "https://fr.wikipedia.org/wiki/Edgar_Allan_Poe" },
  { text: "Le ballet 'Le Lac des cygnes' de Tchaïkovski a été créé en 1876.", url: "https://fr.wikipedia.org/wiki/Le_Lac_des_cygnes" },
  { text: "La Tour Eiffel a été peinte 19 fois et utilise l'équivalent de 60 tonnes de peinture.", url: "https://fr.wikipedia.org/wiki/Tour_Eiffel" },
  { text: "Le premier film d'animation en 3D était 'Toy Story' en 1995.", url: "https://fr.wikipedia.org/wiki/Toy_Story" },
  { text: "Le plus grand musée du monde est le Louvre avec 380 000 œuvres et 606 000 m².", url: "https://fr.wikipedia.org/wiki/Mus%C3%A9_du_Louvre" },
  { text: "Le premier film d'animation Disney 'Blanche-Neige' a coûté 1,4 million de dollars en 1937.", url: "https://fr.wikipedia.org/wiki/Blanche-Neige_et_les_Sept_Nains_(film)" },
  { text: "La symphonie no 9 de Beethoven a été créée en 1824, alors que Beethoven était sourd.", url: "https://fr.wikipedia.org/wiki/Symphonie_no_9_de_Beethoven" },
  { text: "Le premier livre imprimé fut la Bible de Gutenberg en 1455.", url: "https://fr.wikipedia.org/wiki/Bible_de_Gutenberg" },
  { text: "Le plus long poème du monde est 'Le Mahabharata' avec 100 000 couplets.", url: "https://fr.wikipedia.org/wiki/Mahabharata" },
  { text: "Les premiers jeux olympiques dataient de 776 av. JC en Grèce.", url: "https://fr.wikipedia.org/wiki/Jeux_olympiques_anciens" },
  { text: "Le plus ancien instrument de musique connu est une flûte en os de 43 000 ans.", url: "https://fr.wikipedia.org/wiki/Musique" },
  { text: "Le premier film d'animation japonais 'Astro Boy' a été diffusé en 1963.", url: "https://fr.wikipedia.org/wiki/Astro_Boy" },
  { text: "La Joconde a été volée en 1911 et retrouvé en 1913.", url: "https://fr.wikipedia.org/wiki/Joconde" },
  { text: "Le premier film d'animation Disney était 'Blanche-Neige' en 1937.", url: "https://fr.wikipedia.org/wiki/Blanche-Neige_et_les_Sept_Nains_(film)" },
  { text: "Les égyptiens peignaient les hommes en rouge et les femmes en jaune dans leurs fresques.", url: "https://fr.wikipedia.org/wiki/Art_de_l%27%C3%89gypte_ancienne" },
  { text: "Le plus vieux jeu vidéo connu date de 2600 avant JC : Senet, un jeu de plateau égyptien.", url: "https://fr.wikipedia.org/wiki/Senet" },
  { text: "Le premier roman policier de l'histoire est 'Le Crime de la rue Morgue' de Poe en 1841.", url: "https://fr.wikipedia.org/wiki/Edgar_Allan_Poe" },

  // Philosophie & Pensée
  { text: "Le stoïcisme a été fondé par Zénon de Citium vers 300 av. JC à Athènes.", url: "https://fr.wikipedia.org/wiki/Sto%C3%AFcisme" },
  { text: "Le scepticisme philosophique remonte à Pyrrhon d'Élis au IIIe siècle av. JC.", url: "https://fr.wikipedia.org/wiki/Pyrrhon_d%27%C3%89lis" },
  { text: "Le nihilisme n'est pas le désespoir mais la reconnaissance que les valeurs sont construites.", url: "https://fr.wikipedia.org/wiki/Nihilisme" },
  { text: "L'existentialisme de Sartre signifie que 'l'existence précède l'essence'.", url: "https://fr.wikipedia.org/wiki/Existentialisme" },
  { text: "Le pragmatisme de Peirce et James est une philosophie américaine née en 1870.", url: "https://fr.wikipedia.org/wiki/Pragmatisme" },
  { text: "La phénoménologie de Husserl étudie les structures de la conscience.", url: "https://fr.wikipedia.org/wiki/Ph%C3%A9nom%C3%A9nologie" },
  { text: "L'utilitarisme de Bentham et Mill vise le 'plus grand bonheur pour le plus grand nombre'.", url: "https://fr.wikipedia.org/wiki/Utilitarisme" },
  { text: "Le rationalisme de Descartes part du doute pour trouver une certitude indubitable.", url: "https://fr.wikipedia.org/wiki/Rationalisme" },
  { text: "L'empirisme de Locke et Hume dit que toute connaissance vient de l'expérience.", url: "https://fr.wikipedia.org/wiki/Empirisme" },
  { text: "Le humanisme de la Renaissance place l'humain au centre de la réflexion.", url: "https://fr.wikipedia.org/wiki/Humanisme" },
  { text: "La dialectique de Hegel décrit le mouvement de la pensée en thèse-antithèse-synthèse.", url: "https://fr.wikipedia.org/wiki/Dialectique" },
  { text: "L'éthique de Kant repose sur l'impératif catégorique : agir selon des maximes universelles.", url: "https://fr.wikipedia.org/wiki/%C3%89thique_de_Kant" },
  { text: "La métaphysique d'Aristote étudie l'être en tant qu'être.", url: "https://fr.wikipedia.org/wiki/M%C3%A9taphysique" },
  { text: "L'épistémologie de Popper distingue science et non-science par la falsifiabilité.", url: "https://fr.wikipedia.org/wiki/%C3%89pist%C3%A9mologie" },
  { text: "La logique de Russell et Whitehead a tenté de fonder les mathématiques sur la logique.", url: "https://fr.wikipedia.org/wiki/Logique_math%C3%A9matique" },
  { text: "Le scepticisme de Hume remet en question la causalité et l'induction.", url: "https://fr.wikipedia.org/wiki/David_Hume" },
  { text: "Le nihilisme de Nietzsche est une opportunité de créer de nouvelles valeurs.", url: "https://fr.wikipedia.org/wiki/Friedrich_Nietzsche" },
  { text: "L'existentialisme de Heidegger explore le 'Être-et-Temps'.", url: "https://fr.wikipedia.org/wiki/Martin_Heidegger" },
  { text: "Le pragmatisme de Dewey lie philosophie et éducation.", url: "https://fr.wikipedia.org/wiki/John_Dewey" },
  { text: "La phénoménologie de Merleau-Ponty étudie le corps vécu.", url: "https://fr.wikipedia.org/wiki/Maurice_Merleau-Ponty" },
  { text: "L'utilitarisme de Singer applique le principe au bien-être animal.", url: "https://fr.wikipedia.org/wiki/Peter_Singer" },
  { text: "Le rationalisme de Spinoza identifie Dieu à la Nature.", url: "https://fr.wikipedia.org/wiki/Spinoza" },
  { text: "L'empirisme de Berkeley nie l'existence de la matière : 'être c'est être perçu'.", url: "https://fr.wikipedia.org/wiki/George_Berkeley" },
  { text: "Le humanisme de Montaigne explore la diversité des cultures.", url: "https://fr.wikipedia.org/wiki/Montaigne" },
  { text: "La dialectique de Marx inverse celle de Hegel : le matérialisme historique.", url: "https://fr.wikipedia.org/wiki/Karl_Marx" },

  // Économie & Société
  { text: "Le PIB de la France en 2023 était d'environ 3 000 milliards d'euros.", url: "https://fr.wikipedia.org/wiki/Produit_int%C3%A9rieur_brut" },
  { text: "L'inflation en France était de 2% en moyenne sur les 20 dernières années.", url: "https://fr.wikipedia.org/wiki/Inflation" },
  { text: "Le salaire minimum en France (SMIC) était de 1 766,92 € brut par mois en 2024.", url: "https://fr.wikipedia.org/wiki/Salaire_minimum_interprofessionnel_de_croissance" },
  { text: "Le chômage en France était de 7,3% en 2024.", url: "https://fr.wikipedia.org/wiki/Ch%C3%B4mage" },
  { text: "Les 10% les plus riches de la population mondiale détiennent 76% des richesses.", url: "https://fr.wikipedia.org/wiki/%C3%89galit%C3%A9_%C3%A9conomique" },
  { text: "Le coût de la vie a augmenté de 30% en France depuis 2010.", url: "https://fr.wikipedia.org/wiki/Pouvoir_d%27achat" },
  { text: "La dette publique française était de 113% du PIB en 2024.", url: "https://fr.wikipedia.org/wiki/Dette_publique" },
  { text: "Le budget de la Défense française était de 50 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Budget_de_la_D%C3%A9fense" },
  { text: "Le budget de l'Éducation nationale représentait 60 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/%C3%89ducation_nationale" },
  { text: "Le budget de la Santé en France représentait 12% du PIB en 2023.", url: "https://fr.wikipedia.org/wiki/Sant%C3%A9_en_France" },
  { text: "Le budget de la Culture en France était de 22 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Minist%C3%A8re_de_la_Culture_(France)" },
  { text: "Le budget de la Recherche en France était de 23 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Recherche_en_France" },
  { text: "Le budget de l'Enseignement supérieur représentait 30 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Enseignement_sup%C3%A9rieur_en_France" },
  { text: "Le budget de l'Immigration était de 1,5 milliard d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Immigration_en_France" },
  { text: "Le budget de la Justice représentait 10 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Justice_en_France" },
  { text: "Le budget de la Sécurité sociale était de 350 milliards d'euros en 2023.", url: "https://fr.wikipedia.org/wiki/S%C3%A9curit%C3%A9_sociale_(France)" },
  { text: "Le budget de la Ruralité était de 5 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Am%C3%A9nagement_du_territoire" },
  { text: "Le budget de l'Environnement représentait 10 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/%C3%89cologie" },
  { text: "Le budget de la Transition énergétique était de 8 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Transition_%C3%A9nerg%C3%A9tique" },
  { text: "Le budget de la Lutte contre le changement climatique était de 15 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Changement_climatique" },
  { text: "Le budget de la Biodiversité représentait 2 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Biodiversit%C3%A9" },
  { text: "Le budget de la Justice pénale était de 3 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Justice_p%C3%A9nale" },
  { text: "Le budget de la Prévention de la délinquance était de 1 milliard d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/D%C3%A9linquance" },
  { text: "Le budget de la Réinsertion était de 500 millions d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/R%C3%A9insertion" },
  { text: "Le budget de la Protection judiciaire de la jeunesse était de 2 milliards d'euros en 2024.", url: "https://fr.wikipedia.org/wiki/Protection_judiciaire_de_la_jeunesse" },
]

async function main() {
  // Delete existing facts
  const deleted = await prisma.saviezVousFact.deleteMany()
  console.log(`Deleted ${deleted.count} existing facts`)
  
  // Insert new facts
  const data = FACTS.map(f => ({
    text: f.text,
    sourceUrl: f.url,
  }))
  
  const inserted = await prisma.saviezVousFact.createMany({
    data,
  })
  
  console.log(`Inserted ${inserted.count} new facts`)
  
  // Verify
  const count = await prisma.saviezVousFact.count()
  console.log(`Total facts in DB: ${count}`)
  
  const sample = await prisma.saviezVousFact.findMany({ take: 5, orderBy: { id: 'asc' } })
  console.log('\n--- Sample ---')
  for (const f of sample) {
    console.log(f.text.substring(0, 70))
    console.log(`  URL: ${f.sourceUrl}`)
  }
}

main()
  .catch(e => console.error(e))
  .finally(() => prisma.$disconnect())
